{
  "mode": "rule",
  "log-level": "warning",
  "ipv6": true,
  "allow-lan": false,
  "tcp-concurrent": true,
  "dns": {
    "enable": true,
    "listen": "127.0.0.1:1053",
    "enhanced-mode": "fake-ip",
    "fake-ip-range": "198.18.0.1/16",
    "nameserver": [
      "8.8.8.8",
      "1.1.1.1"
    ],
    "fallback": [
      "1.0.0.1",
      "8.8.4.4"
    ]
  },
  "tun": {
    "enable": true,
    "stack": "system",
    "auto-route": true,
    "auto-detect-interface": true,
    "dns-hijack": [
      "any:53"
    ],
    "strict-route": true
  },
  "proxies": [
    {
      "name": "proxy",
      "type": "vless",
      "server": "89.125.140.215",
      "port": 443,
      "uuid": "2ebc0318-fb20-4930-a221-8b52dcec7983",
      "network": "tcp",
      "udp": true,
      "tls": true,
      "flow": "xtls-rprx-vision",
      "servername": "www.amd.com",
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "NzY9iAt-oCOg7yYOMWDsg-xGuWTzXvukYmNKZg0aWQM",
        "short-id": "d111ad8650ec",
        "spider-x": "/ee21da4dc0055b6"
      }
    }
  ],
  "rules": [
    "MATCH,proxy"
  ]
}